name: linter-job
on: [push]
permissions: write-all
jobs:
  linter-job:
    runs-on: ubuntu-latest

    steps:

      - name: Comprobar codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: linter
        run: npx next lint

  cypress-job:
    runs-on: ubuntu-latest

    needs: linter-job

    strategy:
      fail-fast: false

    steps:

      - name: Comprobar codigo
        uses: actions/checkout@v4

      - name: Tests Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        id: cypress
        continue-on-error: true

      - name: Guardar Resultado
        run: echo "${{ steps.cypress.outcome }}" > ./resultado.txt

      - name: Guardar Artefacto
        uses: actions/upload-artifact@v4
        with:
          path: ./resultado.txt
          name: resultado
        continue-on-error: true
  
  add_badge_job:

    runs-on: ubuntu-latest

    needs: cypress-job

    strategy:
      fail-fast: false

    steps:

      - name: Comprobar codigo
        uses: actions/checkout@v4

      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        id: resultado
        with:
          name: resultado

      - name: Usar artefacto
        id: outcome
        run: |
          result=$(cat ./resultado.txt)
          echo "::set-output name=cypress_outcome::${result}"

      - name: Update README with badge
        uses: ./update-readme-action
        with:
          result: ${{ steps.outcome.outputs.cypress_outcome }}

      - name: Commit and push changes to README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with Cypress test result badge"
          git push
       

