name: linter-job
on: [push]
permissions: write-all
jobs:
  linter-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Comprobar codigo
      - uses: actions/checkout@v2

      - name: Instalar dependencias
      - run: npm install

      - name: linter
      - run: npx next lint

