name: linter-job
on: [push]
permissions: write-all
jobs:
  linter-job:
    runs-on: ubuntu-latest

    steps:

      - name: Instalar dependencias
        run: npm install

      - name: linter
        run: npx next lint

  cypress-job:
    runs-on: ubuntu-latest

    needs: linter-job
    
    strategy:
      fail-fast: false

    steps:

      - name: Comprobar codigo
        uses: actions/checkout@v4

      - name: Tests Cypress
        uses: cypress-io/github-action@v6
        continue-on-error: true

      - name: Guardar Resultado
        uses: actions/upload-artifact
        with:
          path: resultados_tests
          name: result.txt

       

